[package]
name = "saccount_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }
validator_derive = "0.16"
thiserror = "1.0" # Pour gérer les erreurs personnalisées